var car = "vitz";
console.log("is car == 'subharu'? I predict false", car == "subharu");
console.log("is car == 'Vitz'? I predict true", car == "vitz");
console.log("is car == 'honda'? I predict false", car == "honda");
console.log("is car >= 'vitz'? I predict flase", car >= "vitz");
console.log("is car <= 'vitz'? I predict false", car <= "vitz");
console.log("is car < 'vitz'? I predict false", car < "vitz");
console.log("is car === 'vitz'? I predict true", car === "vitz");
console.log("is car !== 'vitz'? I predict false", car !== "vitz");
console.log("is car != 'vitz'? I predict false", car != "vitz");
console.log("is car ==== 'Vitz'? I predict true", car == "Vitz");
